In [2]:
"Bismillah"

'Bismillah'

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
df=pd.read_csv("dataset.csv")

In [5]:
df.head()

,Date,Company,R&D_Spending_USD_Mn,AI_Revenue_USD_Mn,AI_Revenue_Growth_%,Event,Stock_Impact_%
0,2015-01-01,OpenAI,5.92,0.63,-36.82,NaN,-0.36
1,2015-01-02,OpenAI,5.41,1.81,80.59,NaN,0.41
2,2015-01-03,OpenAI,4.50,0.61,-38.88,NaN,0.23
3,2015-01-04,OpenAI,5.45,0.95,-5.34,NaN,0.93
4,2015-01-05,OpenAI,3.40,1.48,48.45,NaN,-0.09

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10959 entries, 0 to 10958
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 10959 non-null  str
 1   Company              10959 non-null  str
 2   R&D_Spending_USD_Mn  10959 non-null  float64
 3   AI_Revenue_USD_Mn    10959 non-null  float64
 4   AI_Revenue_Growth_%  10959 non-null  float64
 5   Event                233 non-null    str
 6   Stock_Impact_%       10959 non-null  float64
dtypes: float64(4), str(3)
memory usage: 599.4 KB

In [7]:
#converting the datatype of the column "Date" into daytime format 
pd.to_datetime(df['Date'])

0       2015-01-01
1       2015-01-02
2       2015-01-03
3       2015-01-04
4       2015-01-05
           ...
10954   2024-12-27
10955   2024-12-28
10956   2024-12-29
10957   2024-12-30
10958   2024-12-31
Name: Date, Length: 10959, dtype: datetime64[us]

In [8]:
df.info

<bound method DataFrame.info of              Date Company  R&D_Spending_USD_Mn  AI_Revenue_USD_Mn  \
0      2015-01-01  OpenAI                 5.92               0.63
1      2015-01-02  OpenAI                 5.41               1.81
2      2015-01-03  OpenAI                 4.50               0.61
3      2015-01-04  OpenAI                 5.45               0.95
4      2015-01-05  OpenAI                 3.40               1.48
...           ...     ...                  ...                ...
10954  2024-12-27    Meta               100.19             103.54
10955  2024-12-28    Meta                99.12             102.37
10956  2024-12-29    Meta                98.95             103.11
10957  2024-12-30    Meta               100.74             103.21
10958  2024-12-31    Meta               100.08             103.41

       AI_Revenue_Growth_% Event  Stock_Impact_%
0                   -36.82   NaN           -0.36
1                    80.59   NaN            0.41
2                   -38.88   NaN            0.23
3                    -5.34   NaN            0.93
4                    48.45   NaN           -0.09
...                    ...   ...             ...
10954               417.68   NaN           -0.66
10955               411.86   NaN           -0.57
10956               415.54   NaN           -0.52
10957               416.03   NaN            0.22
10958               417.04   NaN           -0.16

[10959 rows x 7 columns]>

In [9]:
df['Company'].unique()

<StringArray>
['OpenAI', 'Google', 'Meta']
Length: 3, dtype: str

In [10]:
df.head()

,Date,Company,R&D_Spending_USD_Mn,AI_Revenue_USD_Mn,AI_Revenue_Growth_%,Event,Stock_Impact_%
0,2015-01-01,OpenAI,5.92,0.63,-36.82,NaN,-0.36
1,2015-01-02,OpenAI,5.41,1.81,80.59,NaN,0.41
2,2015-01-03,OpenAI,4.50,0.61,-38.88,NaN,0.23
3,2015-01-04,OpenAI,5.45,0.95,-5.34,NaN,0.93
4,2015-01-05,OpenAI,3.40,1.48,48.45,NaN,-0.09

How much amount thecompanies spent of R & D?

In [11]:
print("Companies spending for R&D :")
RD=df.groupby('Company')['R&D_Spending_USD_Mn'].sum()/1000
RD

Companies spending for R&D :

Company
Google    423.34114
Meta      264.53307
OpenAI     26.48277
Name: R&D_Spending_USD_Mn, dtype: float64

In [ ]:
#plotting it  on graph
plt.bar(RD.index, RD.values)
plt.show()

AttributeError: module 'matplotlib' has no attribute 'bar'